modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="minecolonies_skill_change"
version="1.0.0"
displayName="MineColonies Skill Change"
description='''
Adjust MineColonies citizen skills with an item.
'''

[[dependencies.minecolonies_skill_change]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.minecolonies_skill_change]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.minecolonies_skill_change]]
modId="minecolonies"
mandatory=true
versionRange="[1.1,)"
ordering="NONE"
side="BOTH"
