modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Adjust MineColonies citizen skills with an item.
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecolonies"
mandatory=true
versionRange="[${minecolonies_version},)"
ordering="NONE"
side="BOTH"
